### ISSUE TITLE
Feature request: dynamically detect pandoc

### ISSUE THREAD

**Issue by bagnacauda** [ChrisChinchilla/vscode-pandoc#27]
I've just installed your extension, and it's great, but I don't like the fact it defaults to Docker even if I already have pandoc installed. I don't use Docker, so I had to install it, add my user to the docker group etc, then I noticed the option to disable it.

I think it should be the other way around, i.e. if you can't find the executable then you use Docker as a backup.

**Comment by camwheeler** [comment]
That one is on me. The intent with the docker update was to have it _disabled_ by default, and [at a quick glance](https://github.com/ChrisChinchilla/vscode-pandoc/blob/f3ae477a01d7b730e150b1238d9d11a8e31842ba/package.json#L87), this _appears_ to be true even though it isn't. I followed the format of the parameter directly above the option to use docker and it had the default value, a boolean, in quotes, when the json specification clearly supports boolean values. I should have set the value to `false` instead of `"false"`. Both of the parameters below should probably be updated.

```
        "pandoc.render.openViewer": {
          "type": "boolean",
          "default": "true",
          "description": "specify if the extension will open the rendered document in it's default viewer"
        },
        "pandoc.useDocker": {
          "type": "boolean",
          "default": "false",
          "description": "specify if the extension will run pandoc from a docker container"
        }
```

**Comment by ChrisChinchilla** [comment]
Sorry all, I also wasn't receiving GitHub notifications properly, fixed now. And this is also fixed. Thanks!
